app = "ludora-front"
primary_region = "ord"

[build]
  build-target = "runner"
  [build.args]
    VITE_API_BASE = { from_secret = "VITE_API_BASE" }
    VITE_FIREBASE_API_KEY = { from_secret = "VITE_FIREBASE_API_KEY" }
    VITE_FIREBASE_AUTH_DOMAIN = { from_secret = "VITE_FIREBASE_AUTH_DOMAIN" }
    VITE_FIREBASE_PROJECT_ID = { from_secret = "VITE_FIREBASE_PROJECT_ID" }
    VITE_FIREBASE_STORAGE_BUCKET = { from_secret = "VITE_FIREBASE_STORAGE_BUCKET" }
    VITE_FIREBASE_MESSAGING_SENDER_ID = { from_secret = "VITE_FIREBASE_MESSAGING_SENDER_ID" }
    VITE_FIREBASE_APP_ID = { from_secret = "VITE_FIREBASE_APP_ID" }
    VITE_FIREBASE_MEASUREMENT_ID = { from_secret = "VITE_FIREBASE_MEASUREMENT_ID" }

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[machine]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1