// Import entities and User from apiClient.js (our new API client)
import {
  EmailTemplate,
  Settings,
  Category,
  Coupon,
  SupportMessage,
  Notification,
  Product,
  Workshop,
  Course,
  File,
  Tool,
  LessonPlan,
  Purchase,
  Transaction,
  EmailLog,
  Game,
  GameContent,
  AudioFile,
  Word,
  WordEN,
  Image,
  QA,
  Grammar,
  ContentList,
  ContentRelationship,
  SubscriptionPlan,
  WebhookLog,
  PendingSubscription,
  SubscriptionHistory,
  GameSession,
  Attribute,
  GameContentTag,
  ContentTag,
  School,
  Classroom,
  StudentInvitation,
  ParentConsent,
  ClassroomMembership,
  Curriculum,
  CurriculumItem,
  ContentTopic,
  ContentTopicProduct,
  CurriculumItemContentTopic,
  User as ApiUser
} from './apiClient.js';

// Re-export all entities
export {
  EmailTemplate,
  Settings,
  Category,
  Coupon,
  SupportMessage,
  Notification,
  Product,
  Workshop,
  Course,
  File,
  Tool,
  LessonPlan,
  Purchase,
  Transaction,
  EmailLog,
  Game,
  GameContent,
  AudioFile,
  Word,
  WordEN,
  Image,
  QA,
  Grammar,
  ContentList,
  ContentRelationship,
  SubscriptionPlan,
  WebhookLog,
  PendingSubscription,
  SubscriptionHistory,
  GameSession,
  Attribute,
  GameContentTag,
  ContentTag,
  School,
  Classroom,
  StudentInvitation,
  ParentConsent,
  ClassroomMembership,
  Curriculum,
  CurriculumItem,
  ContentTopic,
  ContentTopicProduct,
  CurriculumItemContentTopic,
  ApiUser as User // Ensure latest User object is re-exported
};


