// Import functions from apiClient.js (our new API client)
import {
  sendPaymentConfirmation,
  testPayplusConnection,
  applyCoupon,
  updateExistingRegistrations,
  sendRegistrationEmail,
  handlePayplusCallback,
  createPayplusPaymentPage,
  checkPaymentStatus,
  cleanupStuckPaymentSessions,
  cleanupUserStuckSessions,
  handlePayplusProductCallback,
  processEmailTriggers,
  scheduleEmailProcessor,
  triggerEmailAutomation,
  updateExistingGames,
  uploadVerbsBulk,
  cleanupStaticTexts,
  createPayplusSubscriptionPage,
  handlePayplusSubscriptionCallback,
  testCallback,
  checkSubscriptionStatus,
  processSubscriptionCallbacks,
  getPayplusRecurringStatus,
  cancelPayplusRecurringSubscription,
  deleteFile,
  createSignedUrl,
  initializeSystemEmailTemplates,
  updateSystemEmailTemplates,
  sendInvitationEmails
} from './apiClient.js';

// Re-export all functions
export {
  sendPaymentConfirmation,
  testPayplusConnection,
  applyCoupon,
  updateExistingRegistrations,
  sendRegistrationEmail,
  handlePayplusCallback,
  createPayplusPaymentPage,
  checkPaymentStatus,
  cleanupStuckPaymentSessions,
  cleanupUserStuckSessions,
  handlePayplusProductCallback,
  processEmailTriggers,
  scheduleEmailProcessor,
  triggerEmailAutomation,
  updateExistingGames,
  uploadVerbsBulk,
  cleanupStaticTexts,
  createPayplusSubscriptionPage,
  handlePayplusSubscriptionCallback,
  testCallback,
  checkSubscriptionStatus,
  processSubscriptionCallbacks,
  getPayplusRecurringStatus,
  cancelPayplusRecurringSubscription,
  deleteFile,
  createSignedUrl,
  initializeSystemEmailTemplates,
  updateSystemEmailTemplates,
  sendInvitationEmails
};

