/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register new user account
         * @description Create a new teacher or student account with email and password
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Validation error or user already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/firebase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with Firebase ID token
         * @description Authenticate using Firebase ID token from frontend Firebase Auth
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FirebaseLoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        /** @description HttpOnly auth cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid Firebase token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/student-portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access student portal
         * @description Get student portal access via lobby code, session ID, or teacher invitation
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StudentAccessRequest"];
                };
            };
            responses: {
                /** @description Student portal access granted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentPortalAuthResponse"];
                    };
                };
                /** @description Invalid access code or missing parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Access code not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link-teacher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link student to teacher
         * @description Connect student account to teacher using invitation code (creates parent consent)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeacherInviteLinkRequest"];
                };
            };
            responses: {
                /** @description Successfully linked to teacher */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeacherInviteLinkResponse"];
                    };
                };
                /** @description Invalid invitation code */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded (3 attempts per 15 minutes) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Get new access token using refresh token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description Token refreshed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshTokenResponse"];
                    };
                };
                /** @description Invalid or expired refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout user
         * @description Invalidate user session and clear auth cookie
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Retrieve current authenticated user information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validate-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate current session
         * @description Check if current session is valid and return user data
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session validation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionValidationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available entity types
         * @description Returns information about available entity types in the system
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entity types information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntityTypesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/products/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products with filtering and pagination
         * @description Retrieve paginated list of products with optional filtering by category, type, and search
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (1-based) */
                    page?: number;
                    /** @description Items per page */
                    limit?: number;
                    /** @description Search term for title/description */
                    search?: string;
                    /** @description Filter by category */
                    category?: string;
                    /** @description Filter by product type */
                    product_type?: "file" | "game" | "workshop" | "course" | "tool" | "lesson_plan" | "bundle";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Products list with pagination */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductsListResponse"];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/product/{id}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product details with access information
         * @description Retrieve detailed product information including access control status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product details with access information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductDetailsResponse"];
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @example teacher@example.com
             */
            email: string;
            /** @example securepassword123 */
            password: string;
            /** @example Sarah Cohen */
            fullName?: string;
            /** @example +972501234567 */
            phone?: string;
        };
        FirebaseLoginRequest: {
            /**
             * @description Firebase ID token from frontend authentication
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6IjE...
             */
            idToken: string;
        };
        /** @description Student portal access request (one of lobby_code, session_id, or teacher_invitation_code required) */
        StudentAccessRequest: {
            /**
             * @description Game lobby code for student access
             * @example ABC123
             */
            lobby_code?: string;
            /**
             * @description Game session ID for student access
             * @example session_xyz789
             */
            session_id?: string;
            /**
             * @description Teacher invitation code for linking student to teacher
             * @example DEF456
             */
            teacher_invitation_code?: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            session: {
                /** @example session_abc123 */
                sessionId?: string;
                /**
                 * Format: date-time
                 * @example 2025-01-16T10:00:00Z
                 */
                expiresAt?: string;
            };
            /** @example Login successful */
            message?: string;
        };
        StudentPortalAuthResponse: {
            /**
             * @description Type of student portal access granted
             * @enum {string}
             */
            accessType: "lobby_access" | "session_access" | "teacher_invite" | "authenticated";
            /** @description Context-specific data for the access type */
            sessionContext: Record<string, never>;
            /** @description User object if authenticated, null for anonymous access */
            user?: components["schemas"]["User"];
        };
        TeacherInviteLinkRequest: {
            /**
             * @description Teacher invitation code to link student account
             * @example ABC123
             */
            teacher_invitation_code: string;
        };
        TeacherInviteLinkResponse: {
            /** @example true */
            success: boolean;
            /** @example Successfully linked to teacher */
            message: string;
            teacher?: {
                id?: string;
                full_name?: string;
            };
            /** @description Whether parent consent was created during linking */
            consent_created?: boolean;
        };
        RefreshTokenRequest: {
            /**
             * @description Refresh token for obtaining new access token
             * @example refresh_abc123xyz
             */
            refresh_token: string;
        };
        RefreshTokenResponse: {
            /** @description New JWT access token */
            access_token: string;
            /**
             * @description Token expiration time in seconds
             * @example 3600
             */
            expires_in: number;
            /** @description New refresh token (optional, returned if rotation is enabled) */
            refresh_token?: string | null;
        };
        LogoutResponse: {
            /** @example true */
            success: boolean;
            /** @example Logged out successfully */
            message: string;
        };
        SessionValidationResponse: {
            /**
             * @description Whether the session is valid
             * @example true
             */
            valid: boolean;
            /** @description User object if session is valid */
            user: components["schemas"]["User"];
            /**
             * Format: date-time
             * @example 2025-01-16T10:00:00Z
             */
            expiresAt?: string | null;
        };
        User: {
            /** @example user_abc123 */
            id: string;
            /**
             * Format: email
             * @example teacher@example.com
             */
            email: string;
            /**
             * @example teacher
             * @enum {string}
             */
            role: "student" | "teacher" | "admin";
            /** @example Sarah */
            first_name?: string;
            /** @example Cohen */
            last_name?: string;
            /**
             * Format: date-time
             * @example 2025-01-15T10:00:00Z
             */
            created_at?: string;
        };
        AccessControlResponse: {
            /**
             * @description Whether user can access this content
             * @example true
             */
            hasAccess: boolean;
            /**
             * @description How the user gained access
             * @example purchase
             * @enum {string}
             */
            accessType: "creator" | "purchase" | "subscription_claim" | "student_via_teacher" | "none";
            /**
             * @description Whether user can download content files
             * @example true
             */
            canDownload: boolean;
            /**
             * @description Whether user can see preview/demo
             * @example true
             */
            canPreview: boolean;
            /**
             * @description Whether user can play/use the content
             * @example true
             */
            canPlay: boolean;
            /**
             * @description How many uses remaining (or 'unlimited')
             * @example unlimited
             */
            remainingAllowances: number | "unlimited";
            /**
             * Format: date-time
             * @description When access expires (null = never expires)
             * @example null
             */
            expiresAt?: string | null;
        };
        ErrorResponse: {
            /** @example PRODUCT_NOT_FOUND */
            error: string;
            /** @example Product with ID 'game_123' was not found */
            message: string;
            /** @description Additional error context */
            details?: Record<string, never>;
        };
        EntityListResponse: {
            /** @description Array of entity objects (type varies by entity type) */
            data: Record<string, never>[];
            pagination: {
                /**
                 * @description Total number of entities
                 * @example 150
                 */
                total?: number;
                /**
                 * @description Current page number
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Number of items per page
                 * @example 50
                 */
                limit?: number;
                /**
                 * @description Total number of pages
                 * @example 3
                 */
                pages?: number;
            };
        };
        /** @description Entity creation request (schema varies by entity type) */
        EntityCreateRequest: {
            /** @example My New Entity */
            title?: string;
            /** @example A detailed description */
            description?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Entity update request (partial schema, varies by entity type) */
        EntityUpdateRequest: {
            [key: string]: unknown;
        };
        EntityBulkRequest: {
            /**
             * @description Bulk operation type
             * @example create
             * @enum {string}
             */
            operation: "create" | "update" | "delete";
            /** @description Array of entities to operate on (max 100) */
            data: Record<string, never>[];
        };
        EntityBulkResponse: {
            /** @example true */
            success: boolean;
            results: {
                id?: string;
                /** @enum {string} */
                status?: "success" | "error";
                error?: string | null;
            }[];
            /**
             * @description Total operations attempted
             * @example 50
             */
            total?: number;
            /**
             * @description Number of successful operations
             * @example 48
             */
            successful?: number;
            /**
             * @description Number of failed operations
             * @example 2
             */
            failed?: number;
        };
        ProductBase: {
            /**
             * @description Unique product identifier
             * @example product_abc123
             */
            id: string;
            /**
             * @description Product type discriminator
             * @enum {string}
             */
            product_type: "file" | "lesson_plan" | "game" | "workshop" | "course" | "tool" | "bundle";
            /**
             * @description Product title
             * @example Advanced Memory Game
             */
            title: string;
            /**
             * @description Short product description
             * @example Quick summary of the product
             */
            short_description?: string | null;
            /**
             * @description Full product description (supports rich text HTML)
             * @example A challenging memory game for students with rich HTML formatting
             */
            description?: string | null;
            /**
             * @description Product category
             * @example educational-games
             */
            category?: string | null;
            /**
             * @description Product price in ILS
             * @example 49.9
             */
            price: number;
            /**
             * @description Whether product is published and visible to buyers
             * @example true
             */
            is_published: boolean;
            /**
             * @description Product image filename
             * @example product-image.jpg
             */
            image_filename?: string | null;
            /**
             * @description Whether product has an image asset
             * @default false
             */
            has_image: boolean;
            /**
             * @description Type of marketing video
             * @enum {string|null}
             */
            marketing_video_type?: "youtube" | "uploaded" | null;
            /**
             * @description YouTube video ID or entity ID for uploaded videos
             * @example dQw4w9WgXcQ
             */
            marketing_video_id?: string | null;
            /** @example Product Demo Video */
            marketing_video_title?: string | null;
            /**
             * @description Video duration in seconds
             * @example 180
             */
            marketing_video_duration?: number | null;
            /**
             * @description Product tags for searchability
             * @default []
             * @example [
             *       "math",
             *       "elementary",
             *       "interactive"
             *     ]
             */
            tags: string[];
            /**
             * @description Target audience description
             * @example Elementary students
             */
            target_audience?: string | null;
            /** @description Type-specific attributes (JSONB field) */
            type_attributes?: Record<string, never> | null;
            /**
             * @description Access duration in days (null = lifetime access)
             * @example 365
             */
            access_days?: number | null;
            /**
             * @description ID of the user who created this product
             * @example user_teacher123
             */
            creator_user_id: string;
            /**
             * @description ID of the associated entity record (null for bundles)
             * @example game_abc123
             */
            entity_id: string;
            /**
             * @description Associated content topic
             * @example topic_mathematics
             */
            content_topic_id?: string | null;
            /**
             * Format: date-time
             * @example 2025-01-15T10:00:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2025-01-15T14:30:00Z
             */
            updated_at?: string;
        };
        GameEntity: {
            /**
             * @description Unique game identifier
             * @example game_abc123
             */
            id: string;
            /**
             * @description Type of game
             * @example memory_game
             * @enum {string|null}
             */
            game_type: "scatter_game" | "sharp_and_smooth" | "memory_game" | "ar_up_there" | null;
            /**
             * @description true = דיגיטלי, false = גרסה להדפסה
             * @default true
             * @example true
             */
            digital: boolean;
            /**
             * @description Game-specific settings (JSONB)
             * @example {
             *       "difficulty": "medium",
             *       "time_limit": 60,
             *       "cards_count": 12
             *     }
             */
            game_settings: Record<string, never>;
            /** @description JSON object defining how to query content for this game */
            content_query?: Record<string, never> | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            product_type: "game";
        };
        FileEntity: {
            /**
             * @description Unique file identifier
             * @example file_abc123
             */
            id: string;
            /** @example Worksheet: Math Practice */
            title: string;
            /**
             * @description Original filename (NULL if not uploaded yet)
             * @example math-worksheet.pdf
             */
            file_name?: string | null;
            /**
             * @example pdf
             * @enum {string|null}
             */
            file_type?: "pdf" | "ppt" | "docx" | "zip" | "other" | null;
            /**
             * @description Whether file can be previewed
             * @default true
             */
            allow_preview: boolean;
            /**
             * @description Whether branding is enabled
             * @default true
             */
            add_branding: boolean;
            /** @description File-specific branding settings (JSONB) */
            branding_settings?: Record<string, never> | null;
            /** @description Reference to system_templates for branding */
            branding_template_id?: string | null;
            /**
             * @description Page numbers accessible in preview (null = all pages)
             * @example [
             *       1,
             *       3,
             *       5,
             *       7
             *     ]
             */
            accessible_pages?: number[] | null;
            /** @description Reference to system_templates for watermarks */
            watermark_template_id?: string | null;
            /** @description Custom watermark settings (JSONB) */
            watermark_settings?: Record<string, never> | null;
            /**
             * @description true = asset only (not standalone product)
             * @default false
             */
            is_asset_only: boolean;
            /**
             * @description File format orientation
             * @example pdf-a4-portrait
             * @enum {string|null}
             */
            target_format?: "pdf-a4-portrait" | "pdf-a4-landscape" | "svg-lessonplan" | "unknown" | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            product_type: "file";
        };
        LessonPlanEntity: {
            /** @example lessonplan_abc123 */
            id: string;
            /**
             * @description Theme context like animals, hanukkah, christmas, etc.
             * @example hanukkah
             */
            context?: string | null;
            /**
             * @description JSON configuration for files (roles, connections, slide configs)
             * @example {
             *       "files": [],
             *       "presentation": []
             *     }
             */
            file_configs?: Record<string, never> | null;
            /**
             * @description Whether lesson plan is active/published
             * @default true
             */
            is_active: boolean;
            /**
             * @description Estimated duration in minutes
             * @example 45
             */
            estimated_duration?: number | null;
            /**
             * @description Total number of slides
             * @example 12
             */
            total_slides?: number | null;
            /** @description Notes and instructions for the teacher */
            teacher_notes?: string | null;
            /**
             * @description Slide indices accessible in preview (0-based, null = all)
             * @example [
             *       0,
             *       2,
             *       4
             *     ]
             */
            accessible_slides?: number[] | null;
            /**
             * @description Whether slides can be previewed without purchase
             * @default true
             */
            allow_slide_preview: boolean;
            /** @description Reference to watermark template for slides */
            watermark_template_id?: string | null;
            /** @description Reference to branding template for slides */
            branding_template_id?: string | null;
            /** @description Custom branding configuration (JSONB) */
            branding_settings?: Record<string, never> | null;
            /**
             * @description Whether branding is enabled
             * @default true
             */
            add_branding: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            product_type: "lesson_plan";
        };
        BundleProduct: components["schemas"]["ProductBase"] & {
            /** @description Always null for bundles (no entity table) */
            entity_id?: string | null;
            type_attributes: {
                /**
                 * @description Must be true for bundle products
                 * @enum {boolean}
                 */
                is_bundle: true;
                /** @description Array of bundled products (min 2, max 50) */
                bundle_items: {
                    /**
                     * @description Type of bundled product
                     * @enum {string}
                     */
                    product_type: "file" | "lesson_plan" | "game" | "workshop" | "course" | "tool";
                    /** @description ID of the bundled product */
                    product_id: string;
                }[];
                /**
                 * @description Sum of individual product prices
                 * @example 450
                 */
                original_total_price?: number;
                /**
                 * @description Total savings amount
                 * @example 150
                 */
                savings?: number;
                /**
                 * @description Savings as percentage (min 5%)
                 * @example 33
                 */
                savings_percentage?: number;
            };
        };
        ProductWithAccess: components["schemas"]["ProductBase"] & {
            access?: components["schemas"]["AccessControlResponse"];
            /** @description Associated entity data (null for bundles) */
            entity?: (components["schemas"]["GameEntity"] | components["schemas"]["FileEntity"] | components["schemas"]["LessonPlanEntity"]) | null;
        };
        ProductListResponse: {
            data?: components["schemas"]["ProductWithAccess"][];
            pagination?: {
                /** @example 150 */
                total?: number;
                /** @example 1 */
                page?: number;
                /** @example 50 */
                limit?: number;
                /** @example 3 */
                totalPages?: number;
            };
        };
        CreateProductRequest: {
            /** @enum {string} */
            product_type: "file" | "lesson_plan" | "game" | "workshop" | "course" | "tool" | "bundle";
            title: string;
            short_description?: string;
            description?: string;
            category?: string;
            price: number;
            /** @default false */
            is_published: boolean;
            tags?: string[];
            target_audience?: string;
            /** @description Type-specific attributes (required for bundles) */
            type_attributes?: Record<string, never>;
            access_days?: number | null;
            content_topic_id?: string;
        };
        UpdateProductRequest: {
            title?: string;
            short_description?: string;
            description?: string;
            category?: string;
            price?: number;
            is_published?: boolean;
            tags?: string[];
            target_audience?: string;
            type_attributes?: Record<string, never>;
            access_days?: number | null;
            content_topic_id?: string;
        };
        /** @description Rich JSONB benefits structure with granular access control */
        SubscriptionBenefits: {
            games_access?: {
                /** @example true */
                enabled?: boolean;
                /** @example false */
                unlimited?: boolean;
                /**
                 * @description Monthly limit for game claims (ignored if unlimited=true)
                 * @example 50
                 */
                monthly_limit?: number;
            };
            files_access?: {
                /** @example true */
                enabled?: boolean;
                /** @example true */
                unlimited?: boolean;
                /**
                 * @description Monthly limit (0 if unlimited=true)
                 * @example 0
                 */
                monthly_limit?: number;
            };
            lesson_plans_access?: {
                /** @example true */
                enabled?: boolean;
                /** @example false */
                unlimited?: boolean;
                /** @example 30 */
                monthly_limit?: number;
            };
            workshops_access?: {
                /** @example false */
                enabled?: boolean;
                /** @example false */
                unlimited?: boolean;
                /** @example 0 */
                monthly_limit?: number;
            };
            courses_access?: {
                /** @example false */
                enabled?: boolean;
                /** @example false */
                unlimited?: boolean;
                /** @example 0 */
                monthly_limit?: number;
            };
            tools_access?: {
                /** @example false */
                enabled?: boolean;
                /** @example false */
                unlimited?: boolean;
                /** @example 0 */
                monthly_limit?: number;
            };
            classroom_management?: {
                /** @example true */
                enabled?: boolean;
                /** @example false */
                unlimited_classrooms?: boolean;
                /** @example 10 */
                max_classrooms?: number;
                /** @example 500 */
                max_total_students?: number;
            };
            /**
             * @description Whether user can access reports and analytics
             * @example true
             */
            reports_access?: boolean;
        };
        SubscriptionPlan: {
            /**
             * @description Unique subscription plan identifier
             * @example plan_premium_monthly
             */
            id: string;
            /**
             * @description Subscription plan name
             * @example Premium Monthly
             */
            name: string;
            /**
             * @description Plan description
             * @example Full access to all educational content
             */
            description?: string | null;
            /**
             * @description Base price in ILS before discounts
             * @example 99.9
             */
            price: number;
            /**
             * @description Billing frequency (daily only in staging/dev)
             * @example monthly
             * @enum {string}
             */
            billing_period: "daily" | "monthly" | "yearly";
            /**
             * @description Whether plan has an active discount
             * @example true
             */
            has_discount?: boolean | null;
            /**
             * @description Type of discount applied
             * @example percentage
             * @enum {string|null}
             */
            discount_type?: "percentage" | "fixed" | null;
            /**
             * @description Discount value (percentage or fixed amount)
             * @example 20
             */
            discount_value?: number | null;
            /**
             * Format: date-time
             * @description Discount expiration date
             * @example 2025-12-31T23:59:59Z
             */
            discount_valid_until?: string | null;
            /**
             * @description Whether plan is available for purchase
             * @example true
             */
            is_active: boolean;
            /**
             * @description Whether this is the default plan
             * @example false
             */
            is_default?: boolean | null;
            /**
             * @description Plan tier type
             * @example pro
             * @enum {string|null}
             */
            plan_type?: "free" | "pro" | null;
            benefits: components["schemas"]["SubscriptionBenefits"];
            /**
             * @description Display order for plan listing
             * @example 1
             */
            sort_order?: number | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Subscription: {
            /**
             * @description Unique subscription identifier
             * @example sub_abc123
             */
            id: string;
            /**
             * @description ID of subscribed user
             * @example user_teacher456
             */
            user_id: string;
            /**
             * @description Associated subscription plan
             * @example plan_premium_monthly
             */
            subscription_plan_id: string;
            /**
             * @description Associated transaction for payment tracking
             * @example txn_xyz789
             */
            transaction_id?: string | null;
            /**
             * @description Current subscription status
             * @example active
             * @enum {string}
             */
            status: "pending" | "active" | "cancelled" | "expired" | "failed";
            /**
             * Format: date-time
             * @description Subscription start date
             * @example 2025-01-15T10:00:00Z
             */
            start_date: string;
            /**
             * Format: date-time
             * @description Fixed end date (null for auto-renewing)
             * @example null
             */
            end_date?: string | null;
            /**
             * Format: date-time
             * @description Next billing date for auto-renewal
             * @example 2025-02-15T00:00:00Z
             */
            next_billing_date?: string | null;
            /**
             * Format: date-time
             * @description Cancellation timestamp
             * @example null
             */
            cancelled_at?: string | null;
            /**
             * Format: uuid
             * @description PayPlus recurring subscription identifier
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            payplus_subscription_uid?: string | null;
            /**
             * @description PayPlus-reported subscription status
             * @example active
             * @enum {string|null}
             */
            payplus_status?: "active" | "cancelled" | "expired" | "failed" | "pending" | "suspended" | null;
            /**
             * @description Actual billing amount (after discounts, can be admin-overridden)
             * @example 79.9
             */
            billing_price: number;
            /**
             * @description Original price before discounts
             * @example 99.9
             */
            original_price?: number | null;
            /**
             * @description Discount amount applied
             * @example 20
             */
            discount_amount?: number | null;
            /**
             * @description Billing frequency (daily only in staging/dev)
             * @example monthly
             * @enum {string}
             */
            billing_period: "daily" | "monthly" | "yearly";
            /** @description Additional metadata (JSONB) */
            metadata?: Record<string, never> | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateSubscriptionRequest: {
            /** @example plan_premium_monthly */
            subscription_plan_id: string;
            /** @description Admin override for billing price (optional) */
            billing_price?: number;
            /**
             * Format: date-time
             * @description Custom start date (admin only)
             */
            start_date?: string;
            /**
             * @description Whether to enable auto-renewal
             * @default true
             */
            enableAutoRenewal: boolean;
        };
        UpdateSubscriptionRequest: {
            /** @description Update billing price (admin only) */
            billing_price?: number;
            /**
             * Format: date-time
             * @description Update next billing date
             */
            next_billing_date?: string;
            /**
             * Format: date-time
             * @description Set/update fixed end date
             */
            end_date?: string | null;
        };
        CancelSubscriptionRequest: {
            /**
             * @description Keep subscription active until end date
             * @default false
             */
            keepActiveUntilEndDate: boolean;
            /**
             * @description Cancellation reason
             * @example user_cancelled
             */
            reason?: string;
        };
        SubscriptionPurchase: {
            /**
             * @description Unique subscription purchase identifier
             * @example subpurch_abc123
             */
            id: string;
            /**
             * @description Associated subscription history record
             * @example subhist_xyz789
             */
            subscription_history_id: string;
            /**
             * @description Type of content claimed
             * @example workshop
             * @enum {string}
             */
            purchasable_type: "file" | "lesson_plan" | "game" | "workshop" | "course" | "tool";
            /**
             * @description ID of claimed content
             * @example workshop_abc123
             */
            purchasable_id: string;
            /** @description Flexible JSONB usage tracking */
            usage_tracking?: {
                /**
                 * @description Number of times claimed this month
                 * @example 1
                 */
                monthly_claims?: number;
                /**
                 * @description Total usage count
                 * @example 5
                 */
                total_usage?: number;
                /**
                 * Format: date-time
                 * @description Last access timestamp
                 */
                last_accessed?: string;
                /** @description Additional custom tracking data */
                custom_metadata?: Record<string, never>;
            } | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SubscriptionListResponse: {
            data?: components["schemas"]["Subscription"][];
            pagination?: {
                total?: number;
                page?: number;
                limit?: number;
                totalPages?: number;
            };
        };
        EntityTypesResponse: {
            entityTypes?: {
                name?: string;
                description?: string;
            }[];
        };
        ProductsListResponse: components["schemas"]["ProductListResponse"];
        ProductDetailsResponse: components["schemas"]["ProductWithAccess"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
