name: 'Telegram Notification'
description: 'Send deployment notifications to Telegram'
inputs:
  bot-token:
    description: 'Telegram bot token'
    required: true
  chat-id:
    description: 'Telegram chat ID'
    required: true
  status:
    description: 'Deployment status (started/success/failed)'
    required: true
  service:
    description: 'Service name (API/Frontend)'
    required: true
  details:
    description: 'Additional details for the message'
    required: false
    default: ''
  commit-sha:
    description: 'Commit SHA'
    required: false
    default: ${{ github.sha }}
  commit-message:
    description: 'Commit message'
    required: false
    default: ''
  run-url:
    description: 'GitHub Actions run URL'
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

runs:
  using: 'composite'
  steps:
    - name: Send Telegram notification
      shell: bash
      run: |
        # Load configuration
        CONFIG_FILE="${GITHUB_WORKSPACE}/.github/templates/config.json"
        if [ ! -f "$CONFIG_FILE" ]; then
          MAX_COMMIT_LENGTH=200
        else
          MAX_COMMIT_LENGTH=$(jq -r '.commit_message_max_length // 200' "$CONFIG_FILE")
        fi

        # Load template for current status
        TEMPLATE_FILE="${GITHUB_WORKSPACE}/.github/templates/deployment-${{ inputs.status }}.json"
        if [ ! -f "$TEMPLATE_FILE" ]; then
          echo "Warning: Template for status '${{ inputs.status }}' not found, using defaults"
          TITLE="עדכון פריסה"
          LINK_TEXT="🔗 [View GitHub Actions]"
        else
          TITLE=$(jq -r '.title' "$TEMPLATE_FILE")
          LINK_TEXT=$(jq -r '.link_text' "$TEMPLATE_FILE")
        fi

        # Determine service environment
        SERVICE_NAME="${{ inputs.service }}"
        if [[ "$SERVICE_NAME" == *"Staging"* ]]; then
          ENV="STAGING"
        else
          ENV="PROD"
        fi

        # Determine frontend vs api
        if [[ "$SERVICE_NAME" == *"Frontend"* || "$SERVICE_NAME" == *"Firebase"* ]]; then
          SERVICE_TYPE="FRONTEND"
        else
          SERVICE_TYPE="API"
        fi

        # Get current timestamp (UTC)
        TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")

        # Truncate commit message if too long
        COMMIT_MSG="${{ inputs.commit-message }}"
        if [ ${#COMMIT_MSG} -gt $MAX_COMMIT_LENGTH ]; then
          COMMIT_MSG="${COMMIT_MSG:0:$((MAX_COMMIT_LENGTH-3))}..."
        fi

        # Build simplified message
        MESSAGE="*${TITLE} - ${SERVICE_TYPE} ${ENV}*"
        MESSAGE="$MESSAGE"$'\n'"$TIMESTAMP"
        MESSAGE="$MESSAGE"$'\n'$'\n'"Commit: ${COMMIT_MSG}"
        MESSAGE="$MESSAGE"$'\n'$'\n'"${LINK_TEXT}(${{ inputs.run-url }})"

        # Send to Telegram
        curl -s -X POST "https://api.telegram.org/bot${{ inputs.bot-token }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${{ inputs.chat-id }}\",
            \"text\": \"$MESSAGE\",
            \"parse_mode\": \"Markdown\",
            \"disable_web_page_preview\": true
          }"